export const projectdetails = [
    {
      id: 1,
      title: 'M Rook Solutions V2.0',
      date: 'November 2023 - January 2024',
      tagline: 'A revamp of the interactive CV',
      languages: 'NextJS, React components, GSAP/ScrollTrigger CSS, Chat-GPT, Vercel',
      description: 'The initial version of this site was the first project I had done when I had graduated and there were many things with it that I was not happy with. My skillset at that time was limited and for what it was I thought it wasn\'t too bad of a job.',
      description1: 'This website incorporated skills I had learned and some new ones for this project alone.',
      description2: 'This project features a scrollable homepage with brief sections of the overall site. Animations triggered when coming into view via GSAP/ScrollTrigger was a fun learning curve and the CSS to pull this off challenging. Each of the pages in the NavBar takes the user to a detailed ',
      image: '/currentLogo.png',
      githubLink: '',
    },
    {
      id: 2,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 3,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 4,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 5,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 6,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 7,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 8,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 9,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 10,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 11,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
  ];