export const projectdetails = [
    {
      id: 1,
      title: 'M Rook Solutions V2.0',
      date: 'November 2023 - January 2024',
      tagline: 'A revamp of the interactive CV M Rook Solutions Website.',
      languages: 'NextJS, React components, GSAP/ScrollTrigger CSS, Chat-GPT, Vercel',
      description: 'The initial version of this site was the first project I had done when I had graduated in 2021 and there were many things with it that I was not happy with. My skillset at that time was limited and for what it was, I thought it wasn\'t too bad of a job.',
      description1: 'This website incorporated skills I have learned since and some new ones for this project alone.',
      description2: 'This project features a scrollable homepage with brief sections of the overall site. Animations triggered when coming into view via GSAP/ScrollTrigger was a fun learning curve and the CSS to pull this off challenging. Each of the pages in the NavBar takes the user to a detailed page of that particular section',
      image: '/currentLogo.png',
      githubLink: 'https://github.com/rooky1979/mrooksolutionsv2',
    },
    {
      id: 2,
      title: 'Medical Assistant with Chat-GPT',
      date: 'October 2023',
      tagline: 'An experiment to find out how easy it is to incorporate Chat-GPT into an application.',
      languages: 'NextJS, CSS, Chat-GPT 3.5 API',
      description: 'Being involved in an Generative-AI initiative, I was curious just how hard it was to utilise the Chat-GPT API for an application. ',
      description1: 'I thought of a simple mdical assistant where a user could enter some details and the GPT model could come up with some sort of possible diagnosis.',
      description2: 'I created a quick form in NextJS and the necessary fields. I didn\'t worry too much about user input validation as that wasn\'t the goal of the experiment.',
      description3: 'After reading the docs and trying to decipher how to use the API, it worked and was actually relatively easy to do. The real key was the prompt engineering when preparing the prompt to send to the GPT API.',
      image: '/medicalassist.png',
      githubLink: 'https://github.com/rooky1979/MedicalAssistant',
    },
    {
      id: 3,
      title: 'Various SAPUI5 Fiori and UI5 Web Components projects.',
      date: 'August 2023  - October 2023',
      tagline: 'Various learning projects with SAP Fiori languages and frameworks.',
      languages: 'SAP BTP, Fiori, Fiori Elements, SAPUI5, UI5 Web Components for React',
      description: 'As ABAP is my first stop with work, during downtime or in-between projects, I have been upskilling in various SAP Fiori related small projects to round out my SAP skills. Courses in Fiori Elements, CAP and RAP, and SAPUI5 Web Components for React were done and the link to Github was really just playing with the components and what they looked like.',
      image: '/webcomp.png',
      githubLink: 'https://github.com/rooky1979/SAPUI5-Web-components',
    },
    {
      id: 4,
      title: 'The Ink lab',
      date: 'August 2023  - October 2023',
      tagline: 'A website for a tattoo artist.',
      languages: 'React components, NextJS, CSS, Vercel',
      description: 'Continuing to build on NextJS and React components, this is a website that incorporates some new learned techniques.',
      description1: 'A tattoo artist friend residing in Canada has allowed the use of his IP to allow a personal project to occur. This website incorporates a striking landing page with full-motion video of the artist over a loop displaying a brief outline of his process.',
      description2: 'It contains a showcasing of his portfolio and available art where embla was used to create an image carousel which was new to me. A contact form utilising Mailtrap was set up for users to send email enquiries and bookings. It has a subscriber page so that a user can subscribe to a mailing list using Mailchimp. A blog was created that can be updated via Sanity.io. This project was something to help and continue to build on JavaScript, NextJS and React component programming. Also, it was decided to use just native CSS to really get a handle on styling without any kind of framework. Take it back to basics if you will. The challenges were around creating the new features using Mailchimp/Mailtrap, using Sanity.io and getting the image carousels to work. All new things to learn and enjoyable (if not frustrating at times!).',
      image: '/inkLab.png',
      githubLink: 'https://github.com/rooky1979/inklab',
    },
    {
      id: 5,
      title: 'HIGH NOON GAMBLE Web Application VERSION 2.',
      date: 'February 2023 - March 2023',
      tagline: 'An overhaul of the HIGH NOON GAMBLE web app.',
      languages: 'Node.js, React, NextJS, CSS, Vercel',
      description: 'This was an overhaul of the rather rushed but functional HNG V1 web app.',
      description1: 'The web app was redesigned to incorporate a one-stop-shop dashboard for hosts/co-hosts to have easy access to anything they needed to reduce time with switching between screens. Readings were split up into their own sections as were the required elements for the meeting format.',
      description2: 'Searching and filtering were added to the tools and also the ability to randomise each tool if the person required a random reading and a \"GodShot\" tile was introduced that randomises a reading from any of the tools displaying the reading and the tool from whence it came from. This was great being able to gather their user requirements and be able to take the time to create the application they needed. The app is deployed on Vercel and can be found at https://highnoongamblev2.vercel.app/',
      image: '/hngv2.png',
      githubLink: '',
    },
    {
      id: 6,
      title: 'SAP UI5 HIGH NOON GAMBLE Web Application VERSION 2.',
      date: 'January 2023 - February 2023',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 7,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 8,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 9,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 10,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
    {
      id: 11,
      title: '',
      date: '',
      tagline: '',
      languages: '',
      description: '',
      image: '',
      githubLink: '',
    },
  ];