export const techList1 = [
  "/react.jpeg",
  "/nextjs.png",
  "/nodejs.jpeg",
  "/abap.jpeg",
  "/htmlcss.png",
  "/mongodb.png",
  "/sap.png",
  "/java.jpg",
  "/flutter.png",
  "/dart.png",
  "/github.jpeg",
  "/firebase.png",
  "/heroku.png",
  "/derby.png",
  "/sql.jpeg",
  "/os.png",
  "/virtualbox.jpeg",
  "/scrum.png",
  "/cloud.png",
  "/network.jpg",
  "/sapui5.png",
  "/php.jpeg",
  "/python.jpg",
  "/tailwind.png",
  "/bootstrap.png",
  "/sass.png",
  "/docker.png",
  "/net.png",
  "/redux.png",
  "/javascript.png",
  "/express.png",
];

export const projects = [
  "cinemabooking.png",
  "virtualpet1.png",
  "taxiwebsite1.png",
  "yfm.png",
  "mrooksolns.png",
  "stalls.png",
  "hng.png",
  "hngv2.png",
  "inklab.png",
  "mrooksolnsv2.png",
];

